networks:
  default:
    driver: bridge
    name: roboshop
    # external: true #if if already created network manally then use as true
services:
  catalogue:
    image: ramslella/catalogue:v1
    container_name: catalogue
    depends_on:
      - catalogue

  mongodb:
    image: ramslella/mongod:v1
    container_name: mongodb
   

  